"""initial schema: transactions, categories, budgets, alert_events, audit_log

Revision ID: c1b6c78ff858
Revises:
Create Date: 2026-07-18 19:10:41.760500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1b6c78ff858"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "critical", name="alert_severity"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_key"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action", sa.Enum("create", "update", "delete", name="audit_action"), nullable=False
        ),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "actor_source", sa.Enum("chat", "ui", "scheduler", name="audit_actor"), nullable=False
        ),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categories",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("type", sa.Enum("income", "expense", name="category_type"), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "budgets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("monthly_limit_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("monthly_limit_minor > 0", name="ck_budgets_limit_positive"),
        sa.ForeignKeyConstraint(
            ["category"],
            ["categories.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("income", "expense", name="transaction_type"), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column(
            "source", sa.Enum("chat", "attachment", "ui", name="transaction_source"), nullable=False
        ),
        sa.Column("raw_input", sa.String(length=2000), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_minor > 0", name="ck_transactions_amount_positive"),
        sa.CheckConstraint("length(currency) = 3", name="ck_transactions_currency_iso4217_len"),
        sa.ForeignKeyConstraint(
            ["category"],
            ["categories.key"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("budgets")
    op.drop_table("categories")
    op.drop_table("audit_log")
    op.drop_table("alert_events")
    # ### end Alembic commands ###

    # Alembic's autogenerated drop_table calls don't drop the Postgres ENUM
    # types they created (each is used by exactly one column here) — drop
    # them explicitly so downgrade is a true inverse of upgrade.
    for enum_name in (
        "transaction_type",
        "transaction_source",
        "category_type",
        "audit_action",
        "audit_actor",
        "alert_severity",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
